p 73 db연동 단위테스트 PS E:\books\pythonCleanCodeTDD\superlists> python manage.py test Creating test database for alias 'default'... Traceback (most recent call last):   File "C:\python\python34\lib\site-packages\django\db\backends\utils.py", line 65, in execute     return self.cursor.execute(sql, params)   File "C:\python\python34\lib\site-packages\django\db\backends\sqlite3\base.py", line 485, in execute     return Database.Cursor.execute(self, query, params) sqlite3.OperationalError: no such table: lists_item
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\python\python34\lib\site-packages\django\core\management\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "C:\python\python34\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\python\python34\lib\site-packages\django\core\management\commands\test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "C:\python\python34\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\python\python34\lib\site-packages\django\core\management\commands\test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "C:\python\python34\lib\site-packages\django\core\management\base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "C:\python\python34\lib\site-packages\django\core\management\commands\test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\python\python34\lib\site-packages\django\test\runner.py", line 147, in run_tests
    old_config = self.setup_databases()
  File "C:\python\python34\lib\site-packages\django\test\runner.py", line 109, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "C:\python\python34\lib\site-packages\django\test\runner.py", line 299, in setup_databases
    serialize=connection.settings_dict.get("TEST_SERIALIZE", True),
  File "C:\python\python34\lib\site-packages\django\db\backends\creation.py", line 382, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "C:\python\python34\lib\site-packages\django\db\backends\creation.py", line 418, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "C:\python\python34\lib\site-packages\django\core\serializers\__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "C:\python\python34\lib\site-packages\django\core\serializers\base.py", line 52, in serialize
    for obj in queryset:
  File "C:\python\python34\lib\site-packages\django\db\backends\creation.py", line 414, in get_objects
    for obj in queryset.iterator():
  File "C:\python\python34\lib\site-packages\django\db\models\query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "C:\python\python34\lib\site-packages\django\db\models\sql\compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "C:\python\python34\lib\site-packages\django\db\models\sql\compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "C:\python\python34\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\python\python34\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\python\python34\lib\site-packages\django\utils\six.py", line 549, in reraise
    raise value.with_traceback(tb)
  File "C:\python\python34\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\python\python34\lib\site-packages\django\db\backends\sqlite3\base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: lists_item